package com.ufgov.zc.common.zc.model;

public class HuiyuanAttachinfoStrorage extends ZcBaseBill {
    /**
   * 
   */
  private static final long serialVersionUID = -4841949088263079167L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ATTACHINFO_STRORAGE.ATTACHGUID
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    private String attachguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ATTACHINFO_STRORAGE.ATTACHFILENAME
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    private String attachfilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ATTACHINFO_STRORAGE.CONTENTTYPE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    private String contenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ATTACHINFO_STRORAGE.CLIENGTAG
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    private String cliengtag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ATTACHINFO_STRORAGE.DOCUMENTTYPE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    private String documenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ATTACHINFO_STRORAGE.CLIENTGUID
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    private String clientguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ATTACHINFO_STRORAGE.CONTENT
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.ATTACHGUID
     *
     * @return the value of HUIYUAN_ATTACHINFO_STRORAGE.ATTACHGUID
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public String getAttachguid() {
        return attachguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.ATTACHGUID
     *
     * @param attachguid the value for HUIYUAN_ATTACHINFO_STRORAGE.ATTACHGUID
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public void setAttachguid(String attachguid) {
        this.attachguid = attachguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.ATTACHFILENAME
     *
     * @return the value of HUIYUAN_ATTACHINFO_STRORAGE.ATTACHFILENAME
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public String getAttachfilename() {
        return attachfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.ATTACHFILENAME
     *
     * @param attachfilename the value for HUIYUAN_ATTACHINFO_STRORAGE.ATTACHFILENAME
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public void setAttachfilename(String attachfilename) {
        this.attachfilename = attachfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.CONTENTTYPE
     *
     * @return the value of HUIYUAN_ATTACHINFO_STRORAGE.CONTENTTYPE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public String getContenttype() {
        return contenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.CONTENTTYPE
     *
     * @param contenttype the value for HUIYUAN_ATTACHINFO_STRORAGE.CONTENTTYPE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public void setContenttype(String contenttype) {
        this.contenttype = contenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.CLIENGTAG
     *
     * @return the value of HUIYUAN_ATTACHINFO_STRORAGE.CLIENGTAG
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public String getCliengtag() {
        return cliengtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.CLIENGTAG
     *
     * @param cliengtag the value for HUIYUAN_ATTACHINFO_STRORAGE.CLIENGTAG
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public void setCliengtag(String cliengtag) {
        this.cliengtag = cliengtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.DOCUMENTTYPE
     *
     * @return the value of HUIYUAN_ATTACHINFO_STRORAGE.DOCUMENTTYPE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public String getDocumenttype() {
        return documenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.DOCUMENTTYPE
     *
     * @param documenttype the value for HUIYUAN_ATTACHINFO_STRORAGE.DOCUMENTTYPE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public void setDocumenttype(String documenttype) {
        this.documenttype = documenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.CLIENTGUID
     *
     * @return the value of HUIYUAN_ATTACHINFO_STRORAGE.CLIENTGUID
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public String getClientguid() {
        return clientguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.CLIENTGUID
     *
     * @param clientguid the value for HUIYUAN_ATTACHINFO_STRORAGE.CLIENTGUID
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public void setClientguid(String clientguid) {
        this.clientguid = clientguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.CONTENT
     *
     * @return the value of HUIYUAN_ATTACHINFO_STRORAGE.CONTENT
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ATTACHINFO_STRORAGE.CONTENT
     *
     * @param content the value for HUIYUAN_ATTACHINFO_STRORAGE.CONTENT
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}