package com.ufgov.zc.common.zc.model;

import java.math.BigDecimal;
import java.util.Date;

public class HuiyuanZfcgGongyingyeji extends ZcBaseBill {
    /**
   * 
   */
  private static final long serialVersionUID = -7923039712779454767L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.DANWEIGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String danweiguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String biaoduanguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.PGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String pguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.PNAME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNAME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String biaoduanname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANSIZE
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String biaoduansize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANADDRESS
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String biaoduanaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANMONEY
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private BigDecimal biaoduanmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEINAME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String jianshedanweiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEIGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String jianshedanweiguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAODATE
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private Date zhongbiaodate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.ISGETMONEYONTIME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String isgetmoneyontime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNO
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String biaoduanno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.JIESUANMONEY
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private BigDecimal jiesuanmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.XIANGMUENDTIME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private Date xiangmuendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAORATE
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private BigDecimal zhongbiaorate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HUIYUAN_ZFCG_GONGYINGYEJI.AUDITSTATUS
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    private String auditstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.DANWEIGUID
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.DANWEIGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getDanweiguid() {
        return danweiguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.DANWEIGUID
     *
     * @param danweiguid the value for HUIYUAN_ZFCG_GONGYINGYEJI.DANWEIGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setDanweiguid(String danweiguid) {
        this.danweiguid = danweiguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANGUID
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getBiaoduanguid() {
        return biaoduanguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANGUID
     *
     * @param biaoduanguid the value for HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setBiaoduanguid(String biaoduanguid) {
        this.biaoduanguid = biaoduanguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.PGUID
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.PGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getPguid() {
        return pguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.PGUID
     *
     * @param pguid the value for HUIYUAN_ZFCG_GONGYINGYEJI.PGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setPguid(String pguid) {
        this.pguid = pguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.PNAME
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.PNAME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.PNAME
     *
     * @param pname the value for HUIYUAN_ZFCG_GONGYINGYEJI.PNAME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNAME
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNAME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getBiaoduanname() {
        return biaoduanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNAME
     *
     * @param biaoduanname the value for HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNAME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setBiaoduanname(String biaoduanname) {
        this.biaoduanname = biaoduanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANSIZE
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANSIZE
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getBiaoduansize() {
        return biaoduansize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANSIZE
     *
     * @param biaoduansize the value for HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANSIZE
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setBiaoduansize(String biaoduansize) {
        this.biaoduansize = biaoduansize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANADDRESS
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANADDRESS
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getBiaoduanaddress() {
        return biaoduanaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANADDRESS
     *
     * @param biaoduanaddress the value for HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANADDRESS
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setBiaoduanaddress(String biaoduanaddress) {
        this.biaoduanaddress = biaoduanaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANMONEY
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANMONEY
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public BigDecimal getBiaoduanmoney() {
        return biaoduanmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANMONEY
     *
     * @param biaoduanmoney the value for HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANMONEY
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setBiaoduanmoney(BigDecimal biaoduanmoney) {
        this.biaoduanmoney = biaoduanmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEINAME
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEINAME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getJianshedanweiname() {
        return jianshedanweiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEINAME
     *
     * @param jianshedanweiname the value for HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEINAME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setJianshedanweiname(String jianshedanweiname) {
        this.jianshedanweiname = jianshedanweiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEIGUID
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEIGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getJianshedanweiguid() {
        return jianshedanweiguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEIGUID
     *
     * @param jianshedanweiguid the value for HUIYUAN_ZFCG_GONGYINGYEJI.JIANSHEDANWEIGUID
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setJianshedanweiguid(String jianshedanweiguid) {
        this.jianshedanweiguid = jianshedanweiguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAODATE
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAODATE
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public Date getZhongbiaodate() {
        return zhongbiaodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAODATE
     *
     * @param zhongbiaodate the value for HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAODATE
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setZhongbiaodate(Date zhongbiaodate) {
        this.zhongbiaodate = zhongbiaodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.ISGETMONEYONTIME
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.ISGETMONEYONTIME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getIsgetmoneyontime() {
        return isgetmoneyontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.ISGETMONEYONTIME
     *
     * @param isgetmoneyontime the value for HUIYUAN_ZFCG_GONGYINGYEJI.ISGETMONEYONTIME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setIsgetmoneyontime(String isgetmoneyontime) {
        this.isgetmoneyontime = isgetmoneyontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNO
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNO
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getBiaoduanno() {
        return biaoduanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNO
     *
     * @param biaoduanno the value for HUIYUAN_ZFCG_GONGYINGYEJI.BIAODUANNO
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setBiaoduanno(String biaoduanno) {
        this.biaoduanno = biaoduanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.JIESUANMONEY
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.JIESUANMONEY
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public BigDecimal getJiesuanmoney() {
        return jiesuanmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.JIESUANMONEY
     *
     * @param jiesuanmoney the value for HUIYUAN_ZFCG_GONGYINGYEJI.JIESUANMONEY
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setJiesuanmoney(BigDecimal jiesuanmoney) {
        this.jiesuanmoney = jiesuanmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.XIANGMUENDTIME
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.XIANGMUENDTIME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public Date getXiangmuendtime() {
        return xiangmuendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.XIANGMUENDTIME
     *
     * @param xiangmuendtime the value for HUIYUAN_ZFCG_GONGYINGYEJI.XIANGMUENDTIME
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setXiangmuendtime(Date xiangmuendtime) {
        this.xiangmuendtime = xiangmuendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAORATE
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAORATE
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public BigDecimal getZhongbiaorate() {
        return zhongbiaorate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAORATE
     *
     * @param zhongbiaorate the value for HUIYUAN_ZFCG_GONGYINGYEJI.ZHONGBIAORATE
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setZhongbiaorate(BigDecimal zhongbiaorate) {
        this.zhongbiaorate = zhongbiaorate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.AUDITSTATUS
     *
     * @return the value of HUIYUAN_ZFCG_GONGYINGYEJI.AUDITSTATUS
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public String getAuditstatus() {
        return auditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HUIYUAN_ZFCG_GONGYINGYEJI.AUDITSTATUS
     *
     * @param auditstatus the value for HUIYUAN_ZFCG_GONGYINGYEJI.AUDITSTATUS
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    public void setAuditstatus(String auditstatus) {
        this.auditstatus = auditstatus;
    }
}