package com.ufgov.zc.common.zc.model;

public class ZcEbQuestionWithBLOBs extends ZcEbQuestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_EB_QUEST.ZY_CONTENT
     *
     * @mbggenerated Sun Dec 13 23:03:40 CST 2015
     */
    private String zyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_EB_QUEST.HY_CONTENT
     *
     * @mbggenerated Sun Dec 13 23:03:40 CST 2015
     */
    private String hyContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_EB_QUEST.ZY_CONTENT
     *
     * @return the value of ZC_EB_QUEST.ZY_CONTENT
     *
     * @mbggenerated Sun Dec 13 23:03:40 CST 2015
     */
    public String getZyContent() {
        return zyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_EB_QUEST.ZY_CONTENT
     *
     * @param zyContent the value for ZC_EB_QUEST.ZY_CONTENT
     *
     * @mbggenerated Sun Dec 13 23:03:40 CST 2015
     */
    public void setZyContent(String zyContent) {
        this.zyContent = zyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_EB_QUEST.HY_CONTENT
     *
     * @return the value of ZC_EB_QUEST.HY_CONTENT
     *
     * @mbggenerated Sun Dec 13 23:03:40 CST 2015
     */
    public String getHyContent() {
        return hyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_EB_QUEST.HY_CONTENT
     *
     * @param hyContent the value for ZC_EB_QUEST.HY_CONTENT
     *
     * @mbggenerated Sun Dec 13 23:03:40 CST 2015
     */
    public void setHyContent(String hyContent) {
        this.hyContent = hyContent;
    }
}