package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.HuiyuanZfcgGongyingyeji;

public interface HuiyuanZfcgGongyingyejiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ZFCG_GONGYINGYEJI
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    int insert(HuiyuanZfcgGongyingyeji record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ZFCG_GONGYINGYEJI
     *
     * @mbggenerated Fri Nov 13 03:06:07 CST 2015
     */
    int insertSelective(HuiyuanZfcgGongyingyeji record);
}