package com.ufgov.zc.server.zc.dao;

import java.util.List;

import com.ufgov.zc.common.system.dto.ElementConditionDto;
import com.ufgov.zc.common.zc.model.HuiyuanPeopleblack;

public interface HuiyuanPeopleblackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_PEOPLEBLACK
     *
     * @mbggenerated Mon Nov 16 17:44:24 CST 2015
     */
    int deleteByPrimaryKey(String blguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_PEOPLEBLACK
     *
     * @mbggenerated Mon Nov 16 17:44:24 CST 2015
     */
    int insert(HuiyuanPeopleblack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_PEOPLEBLACK
     *
     * @mbggenerated Mon Nov 16 17:44:24 CST 2015
     */
    int insertSelective(HuiyuanPeopleblack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_PEOPLEBLACK
     *
     * @mbggenerated Mon Nov 16 17:44:24 CST 2015
     */
    HuiyuanPeopleblack selectByPrimaryKey(String blguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_PEOPLEBLACK
     *
     * @mbggenerated Mon Nov 16 17:44:24 CST 2015
     */
    int updateByPrimaryKeySelective(HuiyuanPeopleblack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_PEOPLEBLACK
     *
     * @mbggenerated Mon Nov 16 17:44:24 CST 2015
     */
    int updateByPrimaryKey(HuiyuanPeopleblack record);
    
    List getMainDataLst(ElementConditionDto elementConditionDto);
}