package com.ufgov.zc.server.zc.dao;

import java.util.List;

import com.ufgov.zc.common.system.dto.ElementConditionDto;
import com.ufgov.zc.common.zc.model.HuiyuanUser;

public interface HuiyuanUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_USER
     *
     * @mbggenerated Fri Nov 13 02:53:27 CST 2015
     */
    int deleteByPrimaryKey(String userguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_USER
     *
     * @mbggenerated Fri Nov 13 02:53:27 CST 2015
     */
    int insert(HuiyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_USER
     *
     * @mbggenerated Fri Nov 13 02:53:27 CST 2015
     */
    int insertSelective(HuiyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_USER
     *
     * @mbggenerated Fri Nov 13 02:53:27 CST 2015
     */
    HuiyuanUser selectByPrimaryKey(String userguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_USER
     *
     * @mbggenerated Fri Nov 13 02:53:27 CST 2015
     */
    int updateByPrimaryKeySelective(HuiyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_USER
     *
     * @mbggenerated Fri Nov 13 02:53:27 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(HuiyuanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_USER
     *
     * @mbggenerated Fri Nov 13 02:53:27 CST 2015
     */
    int updateByPrimaryKey(HuiyuanUser record);
    
    List getMainDataLst(ElementConditionDto elementConditionDto);
    
    void updateAuditStatusFN(HuiyuanUser record);
}