package com.ufgov.zc.server.zc.dao;

import java.util.List;

import com.ufgov.zc.common.system.dto.ElementConditionDto;
import com.ufgov.zc.common.zc.model.HuiyuanUnitblack;

public interface HuiyuanUnitblackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_UNITBLACK
     *
     * @mbggenerated Mon Nov 16 17:30:01 CST 2015
     */
    int deleteByPrimaryKey(String blguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_UNITBLACK
     *
     * @mbggenerated Mon Nov 16 17:30:01 CST 2015
     */
    int insert(HuiyuanUnitblack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_UNITBLACK
     *
     * @mbggenerated Mon Nov 16 17:30:01 CST 2015
     */
    int insertSelective(HuiyuanUnitblack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_UNITBLACK
     *
     * @mbggenerated Mon Nov 16 17:30:01 CST 2015
     */
    HuiyuanUnitblack selectByPrimaryKey(String blguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_UNITBLACK
     *
     * @mbggenerated Mon Nov 16 17:30:01 CST 2015
     */
    int updateByPrimaryKeySelective(HuiyuanUnitblack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_UNITBLACK
     *
     * @mbggenerated Mon Nov 16 17:30:01 CST 2015
     */
    int updateByPrimaryKey(HuiyuanUnitblack record);
    
    List getMainDataLst(ElementConditionDto elementConditionDto);
}