package com.ufgov.zc.server.zc.dao;

import java.util.List;

import com.ufgov.zc.common.system.dto.ElementConditionDto;
import com.ufgov.zc.common.zc.model.HuiyuanZfcgGongyingzizhi;

public interface HuiyuanZfcgGongyingzizhiMapper {

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table HUIYUAN_ZFCG_GONGYINGZIZHI
   *
   * @mbggenerated Fri Nov 13 02:53:27 CST 2015
   */
  int deleteByPrimaryKey(String guid);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table HUIYUAN_ZFCG_GONGYINGZIZHI
   *
   * @mbggenerated Fri Nov 13 02:53:27 CST 2015
   */
  int insert(HuiyuanZfcgGongyingzizhi record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table HUIYUAN_ZFCG_GONGYINGZIZHI
   *
   * @mbggenerated Fri Nov 13 02:53:27 CST 2015
   */
  int insertSelective(HuiyuanZfcgGongyingzizhi record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table HUIYUAN_ZFCG_GONGYINGZIZHI
   *
   * @mbggenerated Fri Nov 13 02:53:27 CST 2015
   */
  HuiyuanZfcgGongyingzizhi selectByPrimaryKey(String guid);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table HUIYUAN_ZFCG_GONGYINGZIZHI
   *
   * @mbggenerated Fri Nov 13 02:53:27 CST 2015
   */
  int updateByPrimaryKeySelective(HuiyuanZfcgGongyingzizhi record);

   
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table HUIYUAN_ZFCG_GONGYINGZIZHI
   *
   * @mbggenerated Fri Nov 13 02:53:27 CST 2015
   */
  int updateByPrimaryKey(HuiyuanZfcgGongyingzizhi record);
  
  List getMainDataLst(ElementConditionDto elementConditionDto);
  
  void updateAuditStatusFN(HuiyuanZfcgGongyingzizhi record);
}