package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.HuiyuanAttachinfo;

public interface HuiyuanAttachinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO
     *
     * @mbggenerated Fri Nov 13 03:19:51 CST 2015
     */
    int deleteByPrimaryKey(String attachguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO
     *
     * @mbggenerated Fri Nov 13 03:19:51 CST 2015
     */
    int insert(HuiyuanAttachinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO
     *
     * @mbggenerated Fri Nov 13 03:19:51 CST 2015
     */
    int insertSelective(HuiyuanAttachinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO
     *
     * @mbggenerated Fri Nov 13 03:19:51 CST 2015
     */
    HuiyuanAttachinfo selectByPrimaryKey(String attachguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO
     *
     * @mbggenerated Fri Nov 13 03:19:51 CST 2015
     */
    int updateByPrimaryKeySelective(HuiyuanAttachinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO
     *
     * @mbggenerated Fri Nov 13 03:19:51 CST 2015
     */
    int updateByPrimaryKey(HuiyuanAttachinfo record);
}