package com.ufgov.zc.server.zc.dao;

import java.util.List;

import com.ufgov.zc.common.system.dto.ElementConditionDto;
import com.ufgov.zc.common.zc.model.HuiyuanUnitcominfo;

public interface HuiyuanUnitcominfoMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to
   * the database table HUIYUAN_UNITCOMINFO
   * @mbggenerated Fri Nov 13 01:48:30 CST 2015
   */
  int deleteByPrimaryKey(String danweiguid);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to
   * the database table HUIYUAN_UNITCOMINFO
   * @mbggenerated Fri Nov 13 01:48:30 CST 2015
   */
  int insert(HuiyuanUnitcominfo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to
   * the database table HUIYUAN_UNITCOMINFO
   * @mbggenerated Fri Nov 13 01:48:30 CST 2015
   */
  int insertSelective(HuiyuanUnitcominfo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to
   * the database table HUIYUAN_UNITCOMINFO
   * @mbggenerated Fri Nov 13 01:48:30 CST 2015
   */
  HuiyuanUnitcominfo selectByPrimaryKey(String danweiguid);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to
   * the database table HUIYUAN_UNITCOMINFO
   * @mbggenerated Fri Nov 13 01:48:30 CST 2015
   */
  int updateByPrimaryKeySelective(HuiyuanUnitcominfo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to
   * the database table HUIYUAN_UNITCOMINFO
   * @mbggenerated Fri Nov 13 01:48:30 CST 2015
   */
  int updateByPrimaryKey(HuiyuanUnitcominfo record);

  List getMainDataLst(ElementConditionDto elementConditionDto);

  int insertGysType(HuiyuanUnitcominfo record);

  public void delGysType(String dwGuid);

  public List getGysType(String dwGuid);
}