package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.HuiyuanAttachinfoStrorage;

public interface HuiyuanAttachinfoStrorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO_STRORAGE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    int deleteByPrimaryKey(String attachguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO_STRORAGE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    int insert(HuiyuanAttachinfoStrorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO_STRORAGE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    int insertSelective(HuiyuanAttachinfoStrorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO_STRORAGE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    HuiyuanAttachinfoStrorage selectByPrimaryKey(String attachguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO_STRORAGE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    int updateByPrimaryKeySelective(HuiyuanAttachinfoStrorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO_STRORAGE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(HuiyuanAttachinfoStrorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HUIYUAN_ATTACHINFO_STRORAGE
     *
     * @mbggenerated Fri Nov 13 03:28:28 CST 2015
     */
    int updateByPrimaryKey(HuiyuanAttachinfoStrorage record);
}