package com.ufgov.zc.server.zc.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.system.dto.ElementConditionDto;
import com.ufgov.zc.common.zc.model.ZcEbZxjj;

public interface IZcEbZxjjDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_ZXJJ
     *
     * @mbggenerated Wed Sep 16 00:26:34 CST 2015
     */
    int deleteByPrimaryKey(BigDecimal jjCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_ZXJJ
     *
     * @mbggenerated Wed Sep 16 00:26:34 CST 2015
     */
    int insert(ZcEbZxjj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_ZXJJ
     *
     * @mbggenerated Wed Sep 16 00:26:34 CST 2015
     */
    int insertSelective(ZcEbZxjj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_ZXJJ
     *
     * @mbggenerated Wed Sep 16 00:26:34 CST 2015
     */
    ZcEbZxjj selectByPrimaryKey(BigDecimal jjCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_ZXJJ
     *
     * @mbggenerated Wed Sep 16 00:26:34 CST 2015
     */
    int updateByPrimaryKeySelective(ZcEbZxjj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_ZXJJ
     *
     * @mbggenerated Wed Sep 16 00:26:34 CST 2015
     */
    int updateByPrimaryKey(ZcEbZxjj record);

    List getMainDataLst(ElementConditionDto elementConditionDto);
}