package com.ufgov.zc.server.zc.dao;

import java.math.BigDecimal;
import java.util.List;

import com.ufgov.zc.common.system.dto.ElementConditionDto;
import com.ufgov.zc.common.zc.model.ZcEbZxjjHistory;

public interface IZcEbZxjjHistoryDao {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table ZC_EB_ZXJJ_HISTORY
   *
   * @mbggenerated Wed Sep 16 01:32:01 CST 2015
   */
  int deleteByPrimaryKey(BigDecimal jjCode);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table ZC_EB_ZXJJ_HISTORY
   *
   * @mbggenerated Wed Sep 16 01:32:01 CST 2015
   */
  int insert(ZcEbZxjjHistory record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table ZC_EB_ZXJJ_HISTORY
   *
   * @mbggenerated Wed Sep 16 01:32:01 CST 2015
   */
  int insertSelective(ZcEbZxjjHistory record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table ZC_EB_ZXJJ_HISTORY
   *
   * @mbggenerated Wed Sep 16 01:32:01 CST 2015
   */
  ZcEbZxjjHistory selectByPrimaryKey(BigDecimal jjCode);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table ZC_EB_ZXJJ_HISTORY
   *
   * @mbggenerated Wed Sep 16 01:32:01 CST 2015
   */
  int updateByPrimaryKeySelective(ZcEbZxjjHistory record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table ZC_EB_ZXJJ_HISTORY
   *
   * @mbggenerated Wed Sep 16 01:32:01 CST 2015
   */
  int updateByPrimaryKey(ZcEbZxjjHistory record);
  
  List selectByJjCode(ElementConditionDto dto);
}