package com.ufgov.zc.server.zc.dao;

import java.util.List;

import com.ufgov.zc.common.system.dto.ElementConditionDto;
import com.ufgov.zc.common.zc.model.ZcEbChangdiUsed;

public interface ZcEbChangdiUsedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_CHANGDI_USED
     *
     * @mbggenerated Fri Nov 20 03:51:34 CST 2015
     */
    int deleteByPrimaryKey(String changdiusedid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_CHANGDI_USED
     *
     * @mbggenerated Fri Nov 20 03:51:34 CST 2015
     */
    int insert(ZcEbChangdiUsed record); 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_CHANGDI_USED
     *
     * @mbggenerated Fri Nov 20 03:51:34 CST 2015
     */
    ZcEbChangdiUsed selectByPrimaryKey(String changdiusedid); 

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_CHANGDI_USED
     *
     * @mbggenerated Fri Nov 20 03:51:34 CST 2015
     */
    int updateByPrimaryKey(ZcEbChangdiUsed record);
    
    List getMainDataLst(ElementConditionDto elementConditionDto);
}