package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.ZcEbEntrust;

public interface ZcEbEntrustMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST
	 * @mbggenerated  Mon Nov 09 21:30:12 CST 2015
	 */
	int deleteByPrimaryKey(String sn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST
	 * @mbggenerated  Mon Nov 09 21:30:12 CST 2015
	 */
	int insert(ZcEbEntrust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST
	 * @mbggenerated  Mon Nov 09 21:30:12 CST 2015
	 */
	int insertSelective(ZcEbEntrust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST
	 * @mbggenerated  Mon Nov 09 21:30:12 CST 2015
	 */
	ZcEbEntrust selectByPrimaryKey(String sn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST
	 * @mbggenerated  Mon Nov 09 21:30:12 CST 2015
	 */
	int updateByPrimaryKeySelective(ZcEbEntrust record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST
	 * @mbggenerated  Mon Nov 09 21:30:12 CST 2015
	 */
	int updateByPrimaryKey(ZcEbEntrust record);
}