package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.ZcEbZxjjHistory;

public interface ZcEbZxjjHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_ZXJJ_HISTORY
     *
     * @mbggenerated Fri Nov 13 01:36:08 CST 2015
     */
    int insert(ZcEbZxjjHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_EB_ZXJJ_HISTORY
     *
     * @mbggenerated Fri Nov 13 01:36:08 CST 2015
     */
    int insertSelective(ZcEbZxjjHistory record);
}