package com.ufgov.zc.server.zc.dao;

import com.ufgov.zc.common.zc.model.ZcEbEntrustDetail;

public interface ZcEbEntrustDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST_DETAIL
	 * @mbggenerated  Mon Nov 09 21:33:52 CST 2015
	 */
	int deleteByPrimaryKey(String snd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST_DETAIL
	 * @mbggenerated  Mon Nov 09 21:33:52 CST 2015
	 */
	int insert(ZcEbEntrustDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST_DETAIL
	 * @mbggenerated  Mon Nov 09 21:33:52 CST 2015
	 */
	int insertSelective(ZcEbEntrustDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST_DETAIL
	 * @mbggenerated  Mon Nov 09 21:33:52 CST 2015
	 */
	ZcEbEntrustDetail selectByPrimaryKey(String snd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST_DETAIL
	 * @mbggenerated  Mon Nov 09 21:33:52 CST 2015
	 */
	int updateByPrimaryKeySelective(ZcEbEntrustDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZC_EB_ENTRUST_DETAIL
	 * @mbggenerated  Mon Nov 09 21:33:52 CST 2015
	 */
	int updateByPrimaryKey(ZcEbEntrustDetail record);
}